CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_POINTING=y
CONFIG_INPUT=y

CONFIG_NFCT_PINS_AS_GPIOS=y
CONFIG_I2C_NRFX=y

CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

CONFIG_ZMK_KEYBOARD_NAME="tomkey"

CONFIG_ZMK_DISPLAY=y

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
